name: Publish EURUSD M5 to Gist

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes (UTC)
  workflow_dispatch:        # bouton manuel

# <-- IMPORTANT : donne au workflow le droit d'écrire dans le repo
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run publisher
        env:
          TWELVE_API_KEY: ${{ secrets.TWELVE_API_KEY }}
          GIST_ID:        ${{ secrets.GIST_ID }}
          # Ton token perso (scope "gist") stocké comme secret GH_GIST_TOKEN
          GITHUB_TOKEN:   ${{ secrets.GH_GIST_TOKEN }}
        run: |
          python twelve2gist.py
          
      - name: Upload to Dropbox
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          # upload/overwrite the file
          curl -sS -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer $DROPBOX_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\":\"/eurusd-m5-latest.txt\",\"mode\":\"overwrite\",\"mute\":true}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @eurusd-m5-latest.txt

      - name: Commit to repo if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain eurusd-m5-latest.txt)" ]; then
            git add eurusd-m5-latest.txt
            git commit -m "update feed [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
